//! Keeps SDL's Android JNI glue exports in the final shared library.
//!
//! SDL2's Android backend is driven from Java (`org.libsdl.app.SDLActivity`
//! and friends) through JNI entry points defined in `SDL_android.c`. When SDL
//! is linked statically (the sdl2 crate's `bundled` feature) nothing in the
//! Rust crate references those symbols, so the linker drops them and the Java
//! glue fails with `UnsatisfiedLinkError` at startup.
//!
//! Two things are needed at the final cdylib link:
//! - `-Wl,--undefined=<symbol>` forces the SDL object files that define the
//!   JNI entry points to be pulled in (gc-sections would otherwise drop them).
//! - a second `--version-script` adds the JNI symbols to the exported set.
//!   rustc passes its own version script (which exports only `#[no_mangle]`
//!   symbols and hides everything else); ld.lld merges multiple scripts with
//!   union semantics, so a second script whose `global:` section names the
//!   JNI symbols keeps them exported without hiding rustc's own exports.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("android") {
        return;
    }

    // Function names and their SDL Java-glue class, as generated by the
    // SDL_JAVA_*_INTERFACE macros in SDL_android.c.
    const GLUE: [(&str, &[&str]); 5] = [
        (
            "Java_org_libsdl_app_SDLActivity",
            &[
                "nativeAddTouch",
                "nativeFocusChanged",
                "nativeGetHint",
                "nativeGetHintBoolean",
                "nativeGetVersion",
                "nativeLowMemory",
                "nativePause",
                "nativePermissionResult",
                "nativeQuit",
                "nativeResume",
                "nativeRunMain",
                "nativeSendQuit",
                "nativeSetenv",
                "nativeSetScreenResolution",
                "nativeSetupJNI",
                "onNativeAccel",
                "onNativeClipboardChanged",
                "onNativeDropFile",
                "onNativeKeyboardFocusLost",
                "onNativeKeyDown",
                "onNativeKeyUp",
                "onNativeLocaleChanged",
                "onNativeMouse",
                "onNativeOrientationChanged",
                "onNativeResize",
                "onNativeSoftReturnKey",
                "onNativeSurfaceChanged",
                "onNativeSurfaceCreated",
                "onNativeSurfaceDestroyed",
                "onNativeTouch",
            ],
        ),
        ("Java_org_libsdl_app_SDLAudioManager", &["nativeSetupJNI"]),
        (
            "Java_org_libsdl_app_SDLControllerManager",
            &[
                "nativeAddHaptic",
                "nativeAddJoystick",
                "nativeRemoveHaptic",
                "nativeRemoveJoystick",
                "nativeSetupJNI",
                "onNativeHat",
                "onNativeJoy",
                "onNativePadDown",
                "onNativePadUp",
            ],
        ),
        (
            "Java_org_libsdl_app_SDLInputConnection",
            &["nativeCommitText", "nativeGenerateScancodeForUnichar"],
        ),
        (
            "Java_org_libsdl_app_HIDDeviceManager",
            &[
                "HIDDeviceConnected",
                "HIDDeviceDisconnected",
                "HIDDeviceFeatureReport",
                "HIDDeviceInputReport",
                "HIDDeviceOpenPending",
                "HIDDeviceOpenResult",
                "HIDDeviceRegisterCallback",
                "HIDDeviceReleaseCallback",
            ],
        ),
    ];

    let mut symbols = Vec::new();
    for (class, functions) in GLUE {
        for function in functions {
            let symbol = format!("{class}_{function}");
            // Keep the defining SDL object in the link despite gc-sections.
            println!("cargo:rustc-link-arg=-Wl,--undefined={symbol}");
            symbols.push(symbol);
        }
    }

    // Export them from the cdylib. A merged version script is the only
    // mechanism that beats rustc's own `local: *` script on ld.lld;
    // `--export-dynamic-symbol` is overridden by the version script.
    let mut script = String::from("{\n  global:\n");
    for symbol in &symbols {
        let _ = writeln!(script, "    {symbol};");
    }
    script.push_str("  local:\n    *;\n};\n");
    let out: PathBuf = env::var_os("OUT_DIR").expect("OUT_DIR set").into();
    let path = out.join("sdl-jni-exports.map");
    fs::write(&path, script).expect("write sdl-jni-exports.map");
    println!(
        "cargo:rustc-link-arg=-Wl,--version-script={}",
        path.display()
    );
    println!(
        "cargo:warning=keeping {} SDL Android JNI symbols in the cdylib",
        symbols.len()
    );
}
