(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [verification_extractions_standalone] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module VerificationExtractionsStandalone.

(** Trait declaration: [core::cmp::PartialEq]
    Source: '/rustc/library/core/src/cmp.rs', lines 250:0-250:65
    Name pattern: [core::cmp::PartialEq]
    Visibility: public *)
Record core_cmp_PartialEq_t (Self : Type) (Rhs : Type)
  := mkcore_cmp_PartialEq_t {
  core_cmp_PartialEq_t_eq : Self -> Rhs -> result bool;
}.

Arguments mkcore_cmp_PartialEq_t { _ } { _ }.
Arguments core_cmp_PartialEq_t_eq { _ } { _ } _.

(** Trait declaration: [core::cmp::Eq]
    Source: '/rustc/library/core/src/cmp.rs', lines 338:0-338:58
    Name pattern: [core::cmp::Eq]
    Visibility: public *)
Record core_cmp_Eq_t (Self : Type) := mkcore_cmp_Eq_t {
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst : core_cmp_PartialEq_t Self Self;
  core_cmp_Eq_t_assert_fields_are_eq : Self -> result unit;
}.

Arguments mkcore_cmp_Eq_t { _ }.
Arguments core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst { _ } _.
Arguments core_cmp_Eq_t_assert_fields_are_eq { _ } _.

(** [core::cmp::Eq::assert_fields_are_eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 356:4-356:34
    Name pattern: [core::cmp::Eq::assert_fields_are_eq]
    Visibility: public *)
Axiom core_cmp_Eq_assert_fields_are_eq_default :
  forall{Self : Type} (eqInst : core_cmp_Eq_t Self), Self -> result unit
.

(** Trait declaration: [core::marker::StructuralPartialEq]
    Source: '/rustc/library/core/src/marker.rs', lines 257:0-257:29
    Name pattern: [core::marker::StructuralPartialEq]
    Visibility: public *)
Record core_marker_StructuralPartialEq_t (Self : Type)
  := mkcore_marker_StructuralPartialEq_t{}.

Arguments mkcore_marker_StructuralPartialEq_t { _ }.

(** [verification_extractions_standalone::ProcessorPriority]
    Source: 'verification_extractions_standalone.rs', lines 14:0-20:1
    Visibility: public *)
Inductive ProcessorPriority_t :=
| ProcessorPriority_Default : ProcessorPriority_t
| ProcessorPriority_Global : ProcessorPriority_t
| ProcessorPriority_GlobalSecondChain : ProcessorPriority_t
| ProcessorPriority_HiPriority : ProcessorPriority_t
| ProcessorPriority_Final : ProcessorPriority_t
.

(** [verification_extractions_standalone::{impl core::clone::Clone for verification_extractions_standalone::ProcessorPriority}::clone]:
    Source: 'verification_extractions_standalone.rs', lines 12:9-12:14
    Visibility: public *)
Definition ProcessorPriority_Insts_CoreCloneClone_clone
  (self : ProcessorPriority_t) : result ProcessorPriority_t :=
  Ok self
.

(** Trait implementation: [verification_extractions_standalone::{impl core::clone::Clone for verification_extractions_standalone::ProcessorPriority}]
    Source: 'verification_extractions_standalone.rs', lines 12:9-12:14 *)
Definition ProcessorPriority_Insts_CoreCloneClone : core_clone_Clone
  ProcessorPriority_t := {|
  core_clone_Clone_clone := ProcessorPriority_Insts_CoreCloneClone_clone;
|}.

(** Trait implementation: [verification_extractions_standalone::{impl core::marker::Copy for verification_extractions_standalone::ProcessorPriority}]
    Source: 'verification_extractions_standalone.rs', lines 12:16-12:20 *)
Definition ProcessorPriority_Insts_CoreMarkerCopy : core_marker_Copy
  ProcessorPriority_t := {|
  cloneInst := ProcessorPriority_Insts_CoreCloneClone;
|}.

(** Trait implementation: [verification_extractions_standalone::{impl core::marker::StructuralPartialEq for verification_extractions_standalone::ProcessorPriority}]
    Source: 'verification_extractions_standalone.rs', lines 12:22-12:31 *)
Definition ProcessorPriority_Insts_CoreMarkerStructuralPartialEq :
  core_marker_StructuralPartialEq_t ProcessorPriority_t
  := mkcore_marker_StructuralPartialEq_t.

(** [verification_extractions_standalone::{impl core::cmp::PartialEq<verification_extractions_standalone::ProcessorPriority> for verification_extractions_standalone::ProcessorPriority}::eq]:
    Source: 'verification_extractions_standalone.rs', lines 12:22-12:31
    Visibility: public *)
Definition ProcessorPriority_Insts_CoreCmpPartialEqProcessorPriority_eq
  (self : ProcessorPriority_t) (other : ProcessorPriority_t) : result bool :=
  let self1 := (%%%ERROR: unknown identifier": @discriminant"%%%) self in
  let other1 := (%%%ERROR: unknown identifier": @discriminant"%%%) other in
  Ok (self1 s= other1)
.

(** Trait implementation: [verification_extractions_standalone::{impl core::cmp::PartialEq<verification_extractions_standalone::ProcessorPriority> for verification_extractions_standalone::ProcessorPriority}]
    Source: 'verification_extractions_standalone.rs', lines 12:22-12:31 *)
Definition ProcessorPriority_Insts_CoreCmpPartialEqProcessorPriority :
  core_cmp_PartialEq_t ProcessorPriority_t ProcessorPriority_t := {|
  core_cmp_PartialEq_t_eq :=
    ProcessorPriority_Insts_CoreCmpPartialEqProcessorPriority_eq;
|}.

(** [verification_extractions_standalone::{impl core::cmp::Eq for verification_extractions_standalone::ProcessorPriority}::assert_fields_are_eq]:
    Source: 'verification_extractions_standalone.rs', lines 12:33-12:35
    Visibility: public *)
Definition ProcessorPriority_Insts_CoreCmpEq_assert_fields_are_eq
  (self : ProcessorPriority_t) : result unit :=
  Ok tt
.

(** Trait implementation: [verification_extractions_standalone::{impl core::cmp::Eq for verification_extractions_standalone::ProcessorPriority}]
    Source: 'verification_extractions_standalone.rs', lines 12:33-12:35 *)
Definition ProcessorPriority_Insts_CoreCmpEq : core_cmp_Eq_t
  ProcessorPriority_t := {|
  core_cmp_Eq_tcore_cmp_Eq_t_PartialEqInst :=
    ProcessorPriority_Insts_CoreCmpPartialEqProcessorPriority;
  core_cmp_Eq_t_assert_fields_are_eq :=
    ProcessorPriority_Insts_CoreCmpEq_assert_fields_are_eq;
|}.

(** [verification_extractions_standalone::PROCESSING_ORDER]
    Source: 'verification_extractions_standalone.rs', lines 22:0-28:2
    Visibility: public *)
Definition pROCESSING_ORDER : slice ProcessorPriority_t :=
  array_to_slice
    (mk_array 5%usize [
      ProcessorPriority_HiPriority; ProcessorPriority_Default;
      ProcessorPriority_GlobalSecondChain; ProcessorPriority_Global;
      ProcessorPriority_Final
      ])
.

(** [verification_extractions_standalone::dsp_processing_sequence]: loop body 1:
    Source: 'verification_extractions_standalone.rs', lines 1:0-51:9
    Visibility: public *)
Definition dsp_processing_sequence_loop0_loop0_body
  (items : slice (ProcessorPriority_t * bool)) (priority : ProcessorPriority_t)
  (result1 : alloc_vec_Vec usize) (j : usize) :
  result (control_flow ((alloc_vec_Vec usize) * usize) (alloc_vec_Vec usize))
  :=
  let i := slice_len items in
  if j s< i
  then (
    p <- slice_index_usize items j;
    let (item_prio, _) := p in
    let (_, pending) := p in
    result2 <-
      if pending
      then Ok result1
      else (
        b <-
          ProcessorPriority_Insts_CoreCmpPartialEqProcessorPriority_eq
            item_prio priority;
        if b then alloc_vec_Vec_push result1 j else Ok result1);
    j1 <- usize_add j 1%usize;
    Ok (Cont (result2, j1)))
  else Ok (Done result1)
.

(** [verification_extractions_standalone::dsp_processing_sequence]: loop 1:
    Source: 'verification_extractions_standalone.rs', lines 1:0-51:9
    Visibility: public *)
Definition dsp_processing_sequence_loop0_loop0
  (items : slice (ProcessorPriority_t * bool)) (result1 : alloc_vec_Vec usize)
  (priority : ProcessorPriority_t) (j : usize) :
  result (alloc_vec_Vec usize)
  :=
  loop
    (fun ((result2, j1) : ((alloc_vec_Vec usize) * usize)) =>
      dsp_processing_sequence_loop0_loop0_body items priority result2 j1)
    (result1, j)
.

(** [verification_extractions_standalone::dsp_processing_sequence]: loop body 0:
    Source: 'verification_extractions_standalone.rs', lines 1:0-53:5
    Visibility: public *)
Definition dsp_processing_sequence_loop0_body
  (items : slice (ProcessorPriority_t * bool))
  (order : slice ProcessorPriority_t) (result1 : alloc_vec_Vec usize)
  (i : usize) :
  result (control_flow ((alloc_vec_Vec usize) * usize) (alloc_vec_Vec usize))
  :=
  let i1 := slice_len order in
  if i s< i1
  then (
    priority <- slice_index_usize order i;
    result2 <-
      dsp_processing_sequence_loop0_loop0 items result1 priority 0%usize;
    i2 <- usize_add i 1%usize;
    Ok (Cont (result2, i2)))
  else Ok (Done result1)
.

(** [verification_extractions_standalone::dsp_processing_sequence]: loop 0:
    Source: 'verification_extractions_standalone.rs', lines 1:0-53:5
    Visibility: public *)
Definition dsp_processing_sequence_loop0
  (items : slice (ProcessorPriority_t * bool))
  (order : slice ProcessorPriority_t) (result1 : alloc_vec_Vec usize)
  (i : usize) :
  result (alloc_vec_Vec usize)
  :=
  loop
    (fun ((result2, i1) : ((alloc_vec_Vec usize) * usize)) =>
      dsp_processing_sequence_loop0_body items order result2 i1)
    (result1, i)
.

(** [verification_extractions_standalone::dsp_processing_sequence]:
    Source: 'verification_extractions_standalone.rs', lines 36:0-55:1
    Visibility: public *)
Definition dsp_processing_sequence
  (items : slice (ProcessorPriority_t * bool))
  (order : slice ProcessorPriority_t) :
  result (alloc_vec_Vec usize)
  :=
  dsp_processing_sequence_loop0 items order (alloc_vec_Vec_new usize) 0%usize
.

(** [verification_extractions_standalone::fade_sample]:
    Source: 'verification_extractions_standalone.rs', lines 63:0-70:1
    Visibility: public *)
Definition fade_sample
  (out : f32) (pre : f32) (n : usize) (len : usize) : result f32 :=
  admit
.

(** [verification_extractions_standalone::fade_channel]: loop body 0:
    Source: 'verification_extractions_standalone.rs', lines 75:4-78:5
    Visibility: public *)
Definition fade_channel_loop_body
  (pre : slice f32) (pre_len : usize) (out : slice f32) (n : usize) :
  result (control_flow ((slice f32) * usize) (slice f32))
  :=
  if n s< pre_len
  then (
    fl <- slice_index_usize out n;
    fl1 <- slice_index_usize pre n;
    i <- usize_add n 1%usize;
    fl2 <- fade_sample fl fl1 i pre_len;
    s <- slice_update_usize out n fl2;
    Ok (Cont (s, i)))
  else Ok (Done out)
.

(** [verification_extractions_standalone::fade_channel]: loop 0:
    Source: 'verification_extractions_standalone.rs', lines 75:4-78:5
    Visibility: public *)
Definition fade_channel_loop
  (out : slice f32) (pre : slice f32) (pre_len : usize) (n : usize) :
  result (slice f32)
  :=
  loop
    (fun ((out1, n1) : ((slice f32) * usize)) => fade_channel_loop_body pre
      pre_len out1 n1)
    (out, n)
.

(** [verification_extractions_standalone::fade_channel]:
    Source: 'verification_extractions_standalone.rs', lines 73:0-79:1
    Visibility: public *)
Definition fade_channel
  (out : slice f32) (pre : slice f32) (pre_len : usize) : result (slice f32) :=
  fade_channel_loop out pre pre_len 0%usize
.

(** [verification_extractions_standalone::main]:
    Source: 'verification_extractions_standalone.rs', lines 81:0-84:1 *)
Definition main : result unit :=
  Ok tt.

End VerificationExtractionsStandalone.
