#!/usr/bin/env python3
"""Capture, but never invent, a macOS native-app acceptance workflow.

This driver deliberately has no smoke-test or synthetic-evidence mode.  The
operator performs the documented UI action and presses Return; the driver
then records the real frontmost app's Accessibility description and a screen
capture.  An attestation is written only after every observation is present.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import platform
import plistlib
import subprocess
import sys
import time


def command(*args: str, allow_failure: bool = False) -> str:
    result = subprocess.run(args, text=True, capture_output=True)
    if result.returncode and not allow_failure:
        raise RuntimeError(f"{' '.join(args)} failed: {result.stderr.strip()}")
    return (result.stdout + result.stderr).strip()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def observe(app_name: str) -> str:
    # Accessibility output is an observation of the running native process,
    # not a value supplied by the operator or generated by this script.
    script = f'''tell application "System Events"
if not (exists process "{app_name}") then error "native process is not running"
tell process "{app_name}"
set frontmost to true
return (name of front window) & "\\n" & (entire contents of front window as text)
end tell
end tell'''
    return command("osascript", "-e", script)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("app", type=Path, help="signed .app bundle to exercise")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--step", action="append", required=True,
                        help="required operator step label (repeat in documented order)")
    parser.add_argument("--wait", type=float, default=3.0)
    args = parser.parse_args()
    output = args.output.resolve()
    app = args.app.resolve()
    try:
        if sys.platform != "darwin" or platform.machine() != "arm64":
            raise RuntimeError("real macOS arm64 hardware is required")
        if app.suffix != ".app" or not app.is_dir():
            raise RuntimeError(f"not an application bundle: {app}")
        info = plistlib.loads((app / "Contents/Info.plist").read_bytes())
        app_name = info.get("CFBundleName") or info.get("CFBundleDisplayName")
        if not app_name:
            raise RuntimeError("Info.plist has no application name")
        output.mkdir(parents=True, exist_ok=True)
        attestation = output / "attestation.json"
        if attestation.exists():
            raise RuntimeError(f"refusing to overwrite existing attestation: {attestation}")
        command("codesign", "--verify", "--deep", "--strict", str(app))
        hardware = output / "hardware.txt"
        hardware.write_text(command("system_profiler", "SPHardwareDataType", "SPAudioDataType") + "\n", encoding="utf-8")
        if "Audio" not in hardware.read_text(encoding="utf-8"):
            raise RuntimeError("CoreAudio inventory was empty")
        command("open", "-n", str(app))
        time.sleep(args.wait)
        steps = []
        for index, label in enumerate(args.step, 1):
            if not label.strip():
                raise RuntimeError("step labels must not be empty")
            print(f"Perform step {index}/{len(args.step)} exactly as documented: {label}", flush=True)
            input("Press Return only after the native app visibly completed this step: ")
            observation = output / f"step-{index:02d}-accessibility.txt"
            observation.write_text(observe(str(app_name)), encoding="utf-8")
            screenshot = output / f"step-{index:02d}.png"
            command("screencapture", "-x", "-o", str(screenshot))
            if not screenshot.is_file() or screenshot.stat().st_size == 0:
                raise RuntimeError(f"missing screen capture for step {index}")
            steps.append({"label": label, "accessibility": observation.name,
                          "screenshot": screenshot.name})
        files = [hardware, *[output / item[key] for item in steps for key in ("accessibility", "screenshot")]]
        record = {"schema_version": 1, "status": "passed", "evidence_mode": "macos-native-hardware",
                  "git_revision": command("git", "-C", str(Path(__file__).parents[2]), "rev-parse", "HEAD"),
                  "captured_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(), "app": str(app),
                  "hardware_inventory": hardware.name, "steps": steps,
                  "artifacts_sha256": {path.name: sha256(path) for path in files}}
        temporary = attestation.with_name(attestation.name + ".tmp")
        temporary.write_text(json.dumps(record, sort_keys=True, indent=2) + "\n", encoding="utf-8")
        temporary.replace(attestation)
        print(f"macOS native workflow passed; attestation: {attestation}")
        return 0
    except (OSError, RuntimeError, EOFError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
