//! Rust implementation of the portable stack trace support in `src/stacktrace.c`.

use std::process::Command;
use std::sync::{Mutex, OnceLock};

const OUTPUT_DEFAULT: i32 = 1;
static STATE: OnceLock<Mutex<(Option<String>, i32)>> = OnceLock::new();

fn state() -> &'static Mutex<(Option<String>, i32)> {
    STATE.get_or_init(|| Mutex::new((None, OUTPUT_DEFAULT)))
}

fn shell_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\"'\"'"))
}

fn bounded(dst: &mut [u8], value: &str) -> i32 {
    if dst.is_empty() || value.len() >= dst.len() {
        if let Some(last) = dst.last_mut() {
            *last = 0;
        }
        return -1;
    }
    dst[..value.len()].copy_from_slice(value.as_bytes());
    dst[value.len()] = 0;
    0
}

/// Build an nm command, returning `None` when the input or output is too large.
pub fn build_nm_command(progname: &str) -> Option<String> {
    Some(format!("nm -B {}", shell_quote(progname)))
}

pub fn stacktrace_build_nm_command(dst: &mut [u8], use_gnu_nm: bool, progname: &str) -> i32 {
    let _ = use_gnu_nm; // The C implementation currently emits this prefix on Unix too.
    build_nm_command(progname).map_or(-1, |s| bounded(dst, &s))
}

pub fn build_debugger_command(progname: &str, command_file: &str) -> Option<String> {
    Some(format!(
        "gdb -q {} {} 2>/dev/null <{} >fweelin-stackdump",
        shell_quote(progname),
        std::process::id(),
        shell_quote(command_file)
    ))
}

pub fn stacktrace_build_debugger_command(
    dst: &mut [u8],
    progname: &str,
    command_file: &str,
) -> i32 {
    build_debugger_command(progname, command_file).map_or(-1, |s| bounded(dst, &s))
}

pub fn parse_nm_symbol_line(line: &str) -> Option<(u64, char, String)> {
    let mut p = line.split_whitespace();
    let address = p.next()?;
    let addr = u64::from_str_radix(
        address
            .strip_prefix("0x")
            .or_else(|| address.strip_prefix("0X"))
            .unwrap_or(address),
        16,
    )
    .ok()?;
    let typ = p.next()?.chars().next()?;
    let name = p.next()?.to_owned();
    Some((addr, typ, name))
}

/// C-buffer equivalent of `stacktrace_parse_nm_symbol_line`.
pub fn stacktrace_parse_nm_symbol_line(
    line: &str,
    addr: &mut u64,
    typ: &mut char,
    name: &mut [u8],
) -> i32 {
    if name.is_empty() {
        return 0;
    }
    name[0] = 0;
    let Some((parsed_addr, parsed_type, parsed_name)) = parse_nm_symbol_line(line) else {
        return 0;
    };
    *addr = parsed_addr;
    *typ = parsed_type;
    let n = parsed_name.len().min(name.len() - 1);
    name[..n].copy_from_slice(&parsed_name.as_bytes()[..n]);
    name[n] = 0;
    1
}

/// Byte-oriented counterpart of C's bounded symbol-name copy.
pub fn copy_symbol_name_bytes(src: &[u8], max_len: usize) -> Vec<u8> {
    src.iter()
        .copied()
        .take_while(|byte| *byte != 0)
        .take(max_len)
        .collect()
}

/// UTF-8 convenience wrapper. Use `copy_symbol_name_bytes` for C-byte parity.
pub fn copy_symbol_name(src: &str, max_len: usize) -> String {
    src.chars().take(max_len).collect()
}

pub fn format_symbol_entry(
    index: i32,
    address: u64,
    name: Option<&str>,
    offset: u64,
    typ: char,
) -> String {
    match name.filter(|n| !n.is_empty()) {
        Some(n) => format!("[{index}] 0x{address:08x} <{n} + 0x{offset:x}> {typ}\n"),
        None => format!("[{index}] 0x{address:08x} ???\n"),
    }
}

pub fn stacktrace_copy_symbol_name(dst: &mut [u8], src: &str) -> i32 {
    if dst.is_empty() {
        return -1;
    }
    let n = src.len().min(dst.len() - 1);
    dst[..n].copy_from_slice(&src.as_bytes()[..n]);
    dst[n] = 0;
    0
}

pub fn stacktrace_format_symbol_entry(
    dst: &mut [u8],
    index: i32,
    address: u64,
    name: Option<&str>,
    offset: u64,
    typ: char,
) -> i32 {
    bounded(dst, &format_symbol_entry(index, address, name, offset, typ))
}

fn write_output(bytes: &[u8], handle: i32) {
    #[cfg(unix)]
    {
        let fd = if handle == -1 {
            libc::STDOUT_FILENO
        } else {
            handle
        };
        let mut offset = 0;
        while offset < bytes.len() {
            let n =
                unsafe { libc::write(fd, bytes[offset..].as_ptr().cast(), bytes.len() - offset) };
            if n <= 0 {
                break;
            }
            offset += n as usize;
        }
    }
    #[cfg(not(unix))]
    {
        let _ = handle;
        print!("{}", String::from_utf8_lossy(bytes));
    }
}

fn run_debugger_shell(command: &str) -> bool {
    Command::new("sh").args(["-c", command]).status().is_ok()
}

/// Run a debugger command generated by this module. Returns whether it was launched.
pub fn stack_trace(command_file: Option<&str>) -> bool {
    let prog = state().lock().ok().and_then(|s| s.0.clone());
    let handle = state().lock().map(|s| s.1).unwrap_or(OUTPUT_DEFAULT);
    let Some(prog) = prog else { return false };
    let Some(file) = command_file else {
        write_output(b"No debugger found\n", handle);
        return false;
    };
    let Some(cmd) = build_debugger_command(&prog, file) else {
        return false;
    };
    // `DumpStack` in stacktrace.c deliberately treats a successfully forked
    // shell as success.  The generated command redirects gdb output to
    // fweelin-stackdump, so inspecting captured stdout here would make every
    // normal invocation look like a failure.  Preserve that historical
    // contract, including a non-zero exit from gdb itself.
    if run_debugger_shell(&cmd) {
        return true;
    }
    write_output(b"No debugger found\n", handle);
    false
}

pub fn stack_trace_init(progname: &str, handle: i32) {
    if let Ok(mut s) = state().lock() {
        s.0 = Some(progname.to_owned());
        s.1 = handle;
    }
}
pub fn stack_trace_from_safe_context(file: &str) -> bool {
    // The C API returns 1 for every non-NULL pointer, independently of
    // whether the debugger can actually attach.  `&str` cannot be NULL, so
    // preserve the non-NULL result even for an empty command-file path.
    let _ = stack_trace(Some(file));
    true
}

// Names used by the original C API.
pub use stack_trace as StackTrace;
pub use stack_trace_from_safe_context as StackTraceFromSafeContext;
pub use stack_trace_init as StackTraceInit;

#[cfg(test)]
mod tests {
    use super::*;
    use std::process;

    #[test]
    fn quoting_and_parsing() {
        assert_eq!(shell_quote("it's"), "'it'\"'\"'s'");
        assert_eq!(
            parse_nm_symbol_line("1234 T name"),
            Some((0x1234, 'T', "name".into()))
        );
    }
    #[test]
    fn bounded_output() {
        let mut b = [0; 4];
        assert_eq!(bounded(&mut b, "abcd"), -1);
        assert_eq!(b[3], 0);
    }

    #[test]
    fn c_command_builder_contract() {
        let long = "p".repeat(127);
        let mut small = [b'x'; 32];
        assert_eq!(stacktrace_build_nm_command(&mut small, true, &long), -1);
        assert_eq!(small[31], 0);

        let mut nm = [0; 256];
        assert_eq!(
            stacktrace_build_nm_command(&mut nm, false, "/tmp/fweelin';touch /tmp/pwned #"),
            0
        );
        assert_eq!(
            std::ffi::CStr::from_bytes_until_nul(&nm)
                .unwrap()
                .to_str()
                .unwrap(),
            "nm -B '/tmp/fweelin'\"'\"';touch /tmp/pwned #'"
        );

        let mut debugger = [0; 512];
        assert_eq!(
            stacktrace_build_debugger_command(&mut debugger, "/tmp/fweelin", "/tmp/cmds.gdb"),
            0
        );
        assert_eq!(
            std::ffi::CStr::from_bytes_until_nul(&debugger)
                .unwrap()
                .to_str()
                .unwrap(),
            format!(
                "gdb -q '/tmp/fweelin' {} 2>/dev/null <'/tmp/cmds.gdb' >fweelin-stackdump",
                process::id()
            )
        );
    }

    #[test]
    fn c_nm_parse_and_symbol_copy_contract() {
        let mut address = 0;
        let mut typ = '\0';
        let mut name = [b'x'; 8];
        assert_eq!(
            stacktrace_parse_nm_symbol_line(
                "0x1234abcd T long_symbol",
                &mut address,
                &mut typ,
                &mut name
            ),
            1
        );
        assert_eq!(address, 0x1234_abcd);
        assert_eq!(typ, 'T');
        assert_eq!(&name, b"long_sy\0");

        let mut copied = [b'x'; 8];
        assert_eq!(stacktrace_copy_symbol_name(&mut copied, "123456789"), 0);
        assert_eq!(&copied, b"1234567\0");
        assert_eq!(copy_symbol_name_bytes(b"abc\0def", 8), b"abc");
    }

    #[test]
    fn c_symbol_format_contract() {
        let mut short = [b'q'; 32];
        assert_eq!(
            stacktrace_format_symbol_entry(
                &mut short,
                7,
                0x1234_5678,
                Some(&"A".repeat(255)),
                0x44,
                'T'
            ),
            -1
        );
        assert_eq!(short[31], 0);
        assert_eq!(
            format_symbol_entry(-1, 0x1234, Some("short_name"), 0x20, 't'),
            "[-1] 0x00001234 <short_name + 0x20> t\n"
        );
    }

    #[test]
    fn debugger_shell_attempt_matches_c_even_when_command_fails() {
        // C's DumpStack sets gotSomething after the shell was forked and
        // waited for; it does not inspect the debugger's exit status.
        assert!(run_debugger_shell("exit 127"));
    }
}
